import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parse } from "yaml";
import { createGo2rtc, hardenGo2rtcYaml, withNamedAliases, streamSlug } from "../src/go2rtc.mjs";
import { createState } from "../src/state.mjs";

const originals = {};
before(() => { for (const k of ["log", "warn", "error"]) { originals[k] = console[k]; console[k] = () => {}; } });
after(() => { for (const k of ["log", "warn", "error"]) console[k] = originals[k]; });

test("writeGo2rtc: one ffmpeg copy source per enabled camera, API on loopback only, webrtc off", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-"));
  const cfg = { go2rtcConfig: join(dir, "nested", "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcBin: "go2rtc" };
  const cams = [{ sn: "T8410A", enabled: true }, { sn: "T8113B", enabled: false }, { sn: "T8214C", enabled: true }];
  const g = createGo2rtc({ cfg, state: createState(), listCameras: () => cams });
  const sns = await g.writeGo2rtc();
  assert.deepEqual(sns, ["T8410A", "T8214C"]);
  const text = readFileSync(cfg.go2rtcConfig, "utf8");
  const y = parse(text);
  assert.equal(y.api.listen, "127.0.0.1:1984", "go2rtc API must not be reachable off-host");
  assert.equal(y.webrtc.listen, "", "webrtc disabled (empty listen; go2rtc defaults it ON when the block is absent)");
  assert.equal(y.rtsp.listen, ":8554", "RTSP stays on all interfaces for the display clients");
  assert.deepEqual(y.streams, {
    T8410A: "ffmpeg:http://127.0.0.1:3000/stream/T8410A#video=copy",
    T8214C: "ffmpeg:http://127.0.0.1:3000/stream/T8214C#video=copy",
  });
  assert.match(text, /^# generated by/, "generator header comment preserved");
  assert.doesNotMatch(text, /8555/);
});

test("hardenGo2rtcYaml is idempotent and tolerates a file without webrtc", () => {
  const once = hardenGo2rtcYaml('api:\n  listen: ":1984"\nrtsp:\n  listen: ":8554"\nstreams: {}\n');
  assert.equal(parse(once).api.listen, "127.0.0.1:1984");
  assert.equal(parse(once).webrtc.listen, "");
  assert.equal(hardenGo2rtcYaml(once), once);
});

// The go2rtc web UI lists stream keys, and a wall of serial numbers tells an operator nothing about
// which camera they are looking at.
test("named aliases appear alongside the serial streams, not instead of them", () => {
  const yaml = "streams:\n  T8214A: ffmpeg:http://127.0.0.1:3000/stream/T8214A#video=copy\n";
  const out = withNamedAliases(yaml, [{ sn: "T8214A", name: "Front Door" }]);
  assert.match(out, /T8214A: ffmpeg:/, "the serial stream must survive — RTSP URLs and the wall config use it");
  assert.match(out, /front_door: rtsp:\/\/127\.0\.0\.1:8554\/T8214A/);
});

// A second `ffmpeg:` source would open a second producer and therefore a second P2P session to the
// camera. Proxying the serial stream keeps one upstream producer and costs nothing until viewed.
test("an alias proxies the serial stream rather than opening its own source", () => {
  const yaml = "streams:\n  T8214A: ffmpeg:http://127.0.0.1:3000/stream/T8214A#video=copy\n";
  const out = withNamedAliases(yaml, [{ sn: "T8214A", name: "Front Door" }]);
  assert.equal((out.match(/ffmpeg:/g) ?? []).length, 1, "exactly one upstream producer");
});

test("a name that would collide or slug to nothing is skipped", () => {
  const yaml = "streams:\n  T8214A: ffmpeg:x\n  T8425B: ffmpeg:y\n";
  const out = withNamedAliases(yaml, [
    { sn: "T8214A", name: "Front Door" },
    { sn: "T8425B", name: "front door" }, // same slug as the first
    { sn: "T8030C", name: "!!!" }, // slugs to nothing
    { sn: "T8030D", name: "T8214A" }, // collides with a serial
  ]);
  assert.equal((out.match(/front_door:/g) ?? []).length, 1, "the second camera must not steal the name");
  assert.equal((out.match(/^  T8214A:/gm) ?? []).length, 1, "a name must never overwrite a serial stream");
});

test("streamSlug makes URL-safe keys", () => {
  assert.equal(streamSlug("Solar Wall Light Cam"), "solar_wall_light_cam");
  assert.equal(streamSlug("  Garage – Interior/Door  "), "garage_interior_door");
  assert.equal(streamSlug(""), "");
});
