import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { EventEmitter } from "node:events";
import { randomUUID } from "node:crypto";
import { parse } from "yaml";
import { createGo2rtc, hardenGo2rtcYaml, withNamedStreams, streamKeys, streamSlug } from "../src/go2rtc.mjs";
import { createState } from "../src/state.mjs";

const originals = {};
before(() => { for (const k of ["log", "warn", "error"]) { originals[k] = console[k]; console[k] = () => {}; } });
after(() => { for (const k of ["log", "warn", "error"]) console[k] = originals[k]; });

test("writeGo2rtc: one direct copy source per enabled camera, API on loopback only, webrtc off", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-"));
  const cfg = { go2rtcConfig: join(dir, "nested", "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcBin: "go2rtc" };
  const cams = [{ sn: "T8410A", enabled: true }, { sn: "T8113B", enabled: false }, { sn: "T8214C", enabled: true }];
  const g = createGo2rtc({ cfg, state: createState(), listCameras: () => cams });
  const sns = await g.writeGo2rtc();
  assert.deepEqual(sns, ["T8410A", "T8214C"]);
  const text = readFileSync(cfg.go2rtcConfig, "utf8");
  const y = parse(text);
  assert.equal(y.api.listen, "127.0.0.1:1984", "go2rtc API must not be reachable off-host");
  assert.equal(y.webrtc.listen, "", "webrtc disabled (empty listen; go2rtc defaults it ON when the block is absent)");
  assert.equal(y.rtsp.listen, ":8554", "RTSP stays on all interfaces for the display clients");
  assert.deepEqual(y.streams, {
    T8410A: "http://127.0.0.1:3000/stream/T8410A",
    T8214C: "http://127.0.0.1:3000/stream/T8214C",
  });
  assert.match(text, /^# generated by/, "generator header comment preserved");
  assert.doesNotMatch(text, /8555/);
});

test("hardware transcoding retains the ffmpeg source while copy streams stay direct", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-egress-"));
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcBin: "go2rtc", go2rtcTranscode: "auto" };
  const cams = [{ sn: "T8410A", enabled: true }, { sn: "T8423B", enabled: true }];
  const state = createState();
  state.slots.set("T8410A", { codec: "h264" });
  state.slots.set("T8423B", { codec: "h265" });
  await createGo2rtc({ cfg, state, listCameras: () => cams }).writeGo2rtc();
  const streams = parse(readFileSync(cfg.go2rtcConfig, "utf8")).streams;
  assert.equal(streams.T8410A, "http://127.0.0.1:3000/stream/T8410A");
  assert.equal(streams.T8423B, "ffmpeg:http://127.0.0.1:3000/stream/T8423B#video=h264#hardware");
});

test("copy source uses the configured bridge address", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-address-"));
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "192.0.2.10", port: 3030, go2rtcBin: "go2rtc", go2rtcTranscode: "never" };
  await createGo2rtc({ cfg, state: createState(), listCameras: () => [{ sn: "T8410A", enabled: true }] }).writeGo2rtc();
  assert.equal(parse(readFileSync(cfg.go2rtcConfig, "utf8")).streams.T8410A, "http://192.0.2.10:3030/stream/T8410A");
});

test("IPv6 bridge sources have bracketed URL authorities in generated go2rtc config", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-ipv6-"));
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "::1", port: 3000, go2rtcTranscode: "never" };
  await createGo2rtc({ cfg, state: createState(), listCameras: () => [{ sn: "CAM", name: "Camera", enabled: true }] }).writeGo2rtc();
  assert.equal(parse(readFileSync(cfg.go2rtcConfig, "utf8")).streams.camera, "http://[::1]:3000/stream/CAM");
});

test("hardenGo2rtcYaml is idempotent and tolerates a file without webrtc", () => {
  const once = hardenGo2rtcYaml('api:\n  listen: ":1984"\nrtsp:\n  listen: ":8554"\nstreams: {}\n');
  assert.equal(parse(once).api.listen, "127.0.0.1:1984");
  assert.equal(parse(once).webrtc.listen, "");
  assert.equal(hardenGo2rtcYaml(once), once);
});

// go2rtc lists stream keys, and a wall of serial numbers tells an operator nothing about which camera
// they are looking at. The key IS the name — no serial stream is kept alongside it.
test("streams are keyed by the camera's name, not its serial", () => {
  const yaml = "streams:\n  T8214A: ffmpeg:http://127.0.0.1:3000/stream/T8214A#video=copy\n";
  const out = withNamedStreams(yaml, [{ sn: "T8214A", name: "Front Door" }]);
  assert.match(out, /front_door: ffmpeg:http:\/\/127\.0\.0\.1:3000\/stream\/T8214A#video=copy/);
  assert.doesNotMatch(out, /T8214A:/, "the serial key is replaced, not duplicated");
  assert.equal((out.match(/ffmpeg:/g) ?? []).length, 1, "exactly one producer per camera");
});

// A camera must stay reachable even when its name cannot be used, and must never answer for another.
test("a name that slugs to nothing or collides falls back to the serial", () => {
  const keys = streamKeys([
    { sn: "T8214A", name: "Front Door" },
    { sn: "T8425B", name: "front door" }, // same slug as the first
    { sn: "T8030C", name: "!!!" }, // slugs to nothing
  ]);
  assert.equal(keys.get("T8214A"), "front_door");
  assert.equal(keys.get("T8425B"), "T8425B", "the second camera keeps its serial rather than stealing the name");
  assert.equal(keys.get("T8030C"), "T8030C");
});

test("a camera name cannot claim another camera's serial fallback", () => {
  const cameras = [{ sn: "alpha", name: "Beta" }, { sn: "beta", name: "Beta" }];
  const keys = streamKeys(cameras);
  assert.deepEqual([...keys.values()], ["beta", "beta_2"]);
  assert.equal(streamKeys(cameras.slice(0, 1)).get("alpha"), keys.get("alpha"), "a recovered camera cannot rename an existing stream");
  const yaml = "streams:\n  alpha: source-alpha\n  beta: source-beta\n";
  assert.deepEqual(parse(withNamedStreams(yaml, cameras)).streams, { beta: "source-alpha", beta_2: "source-beta" });
});

test("the source is carried across unchanged, including its transcode suffix", () => {
  const yaml = "streams:\n  T8425B: ffmpeg:http://127.0.0.1:3000/stream/T8425B#video=h264#hardware\n";
  const out = withNamedStreams(yaml, [{ sn: "T8425B", name: "Garage Cam" }]);
  assert.match(out, /garage_cam: ffmpeg:http:\/\/127\.0\.0\.1:3000\/stream\/T8425B#video=h264#hardware/);
});

test("streamSlug makes URL-safe keys", () => {
  assert.equal(streamSlug("Solar Wall Light Cam"), "solar_wall_light_cam");
  assert.equal(streamSlug("  Garage – Interior/Door  "), "garage_interior_door");
  assert.equal(streamSlug(""), "");
});

test("recovered camera is registered through loopback go2rtc without restarting healthy streams", async () => {
  const calls = [];
  let killed = 0;
  const state = createState();
  state.flags.go2rtcProc = { kill: () => { killed++; } };
  const cfg = { go2rtcConfig: "/tmp/unused-go2rtc.yaml", selfHost: "::1", port: 3000, go2rtcTranscode: "never" };
  const go2rtc = createGo2rtc({ cfg, state, listCameras: () => [{ sn: "A", name: "Healthy", enabled: true }] }, {
    fetchImpl: async (url, options) => { calls.push({ url: new URL(url), options }); return { ok: true }; },
  });
  await go2rtc.addGo2rtcCamera({ sn: "B", name: "Recovered", enabled: true }, "recovered");
  assert.equal(calls.length, 1);
  assert.equal(calls[0].url.origin, "http://127.0.0.1:1984");
  assert.equal(calls[0].url.searchParams.get("name"), "recovered");
  assert.equal(calls[0].url.searchParams.get("src"), "http://[::1]:3000/stream/B");
  assert.equal(calls[0].options.method, "PUT");
  assert.equal(killed, 0);
});

test("failed go2rtc registration is reported so rediscovery can retry", async () => {
  const state = createState();
  state.flags.go2rtcProc = { kill: () => {} };
  const cfg = { go2rtcConfig: "/tmp/unused-go2rtc.yaml", selfHost: "127.0.0.1", port: 3000, go2rtcTranscode: "never" };
  const go2rtc = createGo2rtc({ cfg, state, listCameras: () => [] }, { fetchImpl: async () => ({ ok: false, status: 503 }) });
  await assert.rejects(go2rtc.addGo2rtcCamera({ sn: "B", enabled: true }, "b"), /HTTP 503/);
});

test("recovered camera is written to next go2rtc config while the child is down", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-recover-"));
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcTranscode: "never" };
  const healthy = { sn: "A", name: "Healthy", enabled: true };
  const recovered = { sn: "B", name: "Recovered", enabled: true };
  const go2rtc = createGo2rtc({ cfg, state: createState(), listCameras: () => [healthy] }, { fetchImpl: () => { throw new Error("must not call API while stopped"); } });
  await go2rtc.addGo2rtcCamera(recovered, "recovered");
  assert.deepEqual(parse(readFileSync(cfg.go2rtcConfig, "utf8")).streams, {
    healthy: "http://127.0.0.1:3000/stream/A",
    recovered: "http://127.0.0.1:3000/stream/B",
  });
});

test("a newly learned codec updates only that go2rtc stream and leaves the child running", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-codec-"));
  const cameras = [{ sn: "A", name: "Healthy", enabled: true }, { sn: "B", name: "Recovered", enabled: true }];
  const state = createState();
  const calls = [];
  let killed = 0;
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcTranscode: "auto" };
  const go2rtc = createGo2rtc({ cfg, state, listCameras: () => cameras }, {
    fetchImpl: async (url) => { calls.push(new URL(url)); return { ok: true }; },
  });
  await go2rtc.writeGo2rtc();
  state.flags.ready = true;
  state.flags.go2rtcProc = { kill: () => { killed++; } };
  state.slots.set("B", { codec: "h265" });
  await go2rtc.syncGo2rtc();
  assert.equal(calls.length, 1);
  assert.equal(calls[0].searchParams.get("name"), "recovered");
  assert.equal(calls[0].searchParams.get("src"), "ffmpeg:http://127.0.0.1:3000/stream/B#video=h264#hardware");
  assert.equal(killed, 0);
});

test("failed codec update retries without restarting go2rtc", async () => {
  const dir = mkdtempSync(join(tmpdir(), "ewb-go2rtc-codec-"));
  const state = createState();
  const timers = [];
  let calls = 0;
  const cfg = { go2rtcConfig: join(dir, "go2rtc.yaml"), selfHost: "127.0.0.1", port: 3000, go2rtcTranscode: "auto" };
  const camera = { sn: "B", name: "Recovered", enabled: true };
  const go2rtc = createGo2rtc({ cfg, state, listCameras: () => [camera] }, {
    fetchImpl: async () => ({ ok: ++calls > 1, status: 503 }),
    setTimer: (fn) => { const timer = { fn, cleared: false }; timers.push(timer); return timer; },
    clearTimer: (timer) => { timer.cleared = true; },
  });
  await go2rtc.writeGo2rtc();
  state.flags.ready = true;
  state.flags.go2rtcProc = { kill: () => {} };
  state.slots.set("B", { codec: "h265" });
  await assert.rejects(go2rtc.syncGo2rtc(), /HTTP 503/);
  assert.equal(timers.length, 1);
  timers[0].fn();
  await go2rtc.syncGo2rtc();
  assert.equal(calls, 2);
  go2rtc.stopGo2rtc();
  assert.equal(timers[0].cleared, false, "completed retry leaves no pending timer");
});

test("a real missing go2rtc binary schedules a retry after error and close", async () => {
  const state = createState();
  const timers = [];
  const cfg = { go2rtcBin: join(tmpdir(), `no-go2rtc-${randomUUID()}`), go2rtcConfig: "/tmp/unused-go2rtc.yaml" };
  const runner = createGo2rtc({ cfg, state }, { setTimer: (fn) => { const timer = { fn }; timers.push(timer); return timer; }, clearTimer: () => {} });
  runner.startGo2rtc();
  const child = state.flags.go2rtcProc;
  await new Promise((resolve) => child.once("close", resolve));
  assert.equal(state.flags.go2rtcProc, undefined);
  assert.equal(timers.length, 1, "spawn error and close must produce one retry");
  runner.stopGo2rtc();
});

test("go2rtc recovers after a launch failure and stop cancels pending restarts", () => {
  const state = createState();
  const children = [];
  const timers = [];
  const runner = createGo2rtc({ cfg: { go2rtcBin: "go2rtc", go2rtcConfig: "/tmp/unused-go2rtc.yaml" }, state }, {
    retryDelayMs: 50,
    spawnImpl: () => {
      const child = new EventEmitter();
      child.kill = () => { child.emit("exit", 0, "SIGTERM"); return true; };
      children.push(child);
      return child;
    },
    setTimer: (fn, ms) => { const timer = { fn, ms, cleared: false }; timers.push(timer); return timer; },
    clearTimer: (timer) => { timer.cleared = true; },
  });
  runner.startGo2rtc();
  children[0].emit("error", new Error("ENOENT"));
  children[0].emit("error", new Error("late duplicate"));
  children[0].emit("close", -2);
  assert.equal(timers.length, 1);
  assert.equal(timers[0].ms, 50);
  timers[0].fn();
  assert.equal(children.length, 2);
  assert.equal(state.flags.go2rtcProc, children[1]);
  children[1].emit("exit", 1);
  children[1].emit("close", 1);
  assert.equal(timers.length, 2, "exit and close must produce one retry");
  runner.stopGo2rtc();
  assert.equal(timers[1].cleared, true);
  assert.equal(state.flags.go2rtcProc, undefined);
});
